worlds:
    world:
        whitelist: world.whitelist.txt
        interventionMessage: "Nope, bad, bad cat!"
        restrictedEvents:
            - org.bukkit.event.block.BlockPlaceEvent
            - org.bukkit.event.block.BlockBreakEvent
        enableTeleport: true
        teleportDestination:
            world: world_nether
            x: 0.0
            y: 0.0
            z: 0.0
    world_nether:
        restrictedEvents:
            - org.bukkit.event.player.PlayerInteractEvent
            - org.bukkit.event.player.PlayerInteractEntityEvent
            - org.bukkit.event.entity.EntityDamageByEntityEvent
        enableTeleport: true
        teleportDestination:
            world: world_the_end
            x: 0.0
            y: 0.0
            z: 0.0
    world_the_end:
        whitelist: world.whitelist.txt
        restrictedEvents:
            - org.bukkit.event.player.PlayerInteractEvent
            - org.bukkit.event.player.PlayerInteractEntityEvent
            - org.bukkit.event.entity.EntityDamageByEntityEvent
        enableTeleport: true
        teleportDestination:
            world: world
            x: 0.0
            y: 0.0
            z: 0.0
