name: ${project.name}
author: Zw0
version: ${project.version}
description: ${project.description}

main: ${project.groupId}.${project.artifactId}.${project.name}
load: POSTWORLD

commands:
  cr:
    description: Manages CatRestrictor whitelists
    usage: |
           Usage:
               /<command> add|rm <worldname> <playername>
               /<command> reload
           Examples:
               /<command> add world Notch
               /<command> rm world Notch
               /<command> reload
